export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const TO_DO_ROUTE = '/todo'
export const TO_BUY_ROUTE = '/buy'
export const DONE_ROUTE = '/done'
export const MAIN_ROUTE = '/'
export const NOTE_ROUTE = '/note'